name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy
      run:
        npm install && npm run demo:build
        git add .
        git commit -m 'push demo'
        git push      